create table suppliers (
    id bigint generated by default as identity primary key,
    name varchar(255) not null unique,
    email varchar(255),
    lead_time_days integer not null,
    delayed boolean not null
);

create table products (
    id bigint generated by default as identity primary key,
    sku varchar(255) not null unique,
    name varchar(255) not null,
    category varchar(255) not null,
    stock integer not null,
    reorder_point integer not null,
    average_daily_demand integer not null,
    unit_cost numeric(12, 2) not null,
    supplier_id bigint,
    updated_at timestamp with time zone not null,
    constraint fk_products_supplier foreign key (supplier_id) references suppliers (id)
);

create table inventory_movements (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    quantity_change integer not null,
    reason varchar(255) not null,
    created_at timestamp with time zone not null,
    constraint fk_inventory_movements_product foreign key (product_id) references products (id)
);

create table activity_logs (
    id bigint generated by default as identity primary key,
    type varchar(255) not null,
    entity_type varchar(255) not null,
    entity_id bigint,
    title varchar(255) not null,
    details varchar(1200) not null,
    created_at timestamp with time zone not null
);

create table purchase_orders (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    supplier_id bigint,
    quantity integer not null,
    status varchar(40) not null,
    expected_delivery_date date,
    note varchar(600),
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_purchase_orders_product foreign key (product_id) references products (id),
    constraint fk_purchase_orders_supplier foreign key (supplier_id) references suppliers (id)
);

create index idx_products_supplier_id on products (supplier_id);
create index idx_inventory_movements_product_id on inventory_movements (product_id);
create index idx_inventory_movements_created_at on inventory_movements (created_at);
create index idx_activity_logs_created_at on activity_logs (created_at);
create index idx_purchase_orders_product_id on purchase_orders (product_id);
create index idx_purchase_orders_supplier_id on purchase_orders (supplier_id);
create index idx_purchase_orders_status on purchase_orders (status);
